from __future__ import annotations

from datetime import date
import hashlib
from pathlib import Path
import re

import numpy as np
import pandas as pd

CACHE_DIR = Path(__file__).resolve().parent / ".cache" / "market"


def _standardize(raw: pd.DataFrame) -> pd.DataFrame:
    df = raw.copy(); df.columns = [str(c).strip().lower() for c in df.columns]
    aliases = {"time":"date", "tradingdate":"date", "indexvalue":"close", "value":"close"}
    df = df.rename(columns={k:v for k,v in aliases.items() if k in df.columns})
    if "date" not in df.columns:
        if isinstance(df.index, pd.DatetimeIndex):
            df = df.reset_index().rename(columns={df.index.name or "index":"date"})
        else: raise ValueError("Market response has no date column")
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    for c in ["open","high","low","close","volume"]:
        if c in df: df[c] = pd.to_numeric(df[c], errors="coerce")
    if "close" not in df: raise ValueError("Market response has no close column")
    for c in ["open","high","low"]:
        if c not in df: df[c] = df["close"]
    if "volume" not in df: df["volume"] = np.nan
    return df[["date","open","high","low","close","volume"]].dropna(subset=["date","close"]).sort_values("date")


def _vnstock(symbol: str, start: str, end: str, source: str) -> tuple[pd.DataFrame,str]:
    errors=[]
    # Sponsor/Unified UI route.
    try:
        from vnstock import Market
        return _standardize(Market().index(symbol).ohlcv(start=start,end=end,interval="1D")), "Vnstock Live / UI"
    except Exception as exc: errors.append(f"Market:{type(exc).__name__}")
    try:
        from vnstock_data import Market
        return _standardize(Market().index(symbol).ohlcv(start=start,end=end,interval="1D")), "Vnstock Live / Data"
    except Exception as exc: errors.append(f"vnstock_data:{type(exc).__name__}")
    # Current Quote API: KBS first, then the configured source and VCI.
    for provider in list(dict.fromkeys(["KBS", source.upper(), "VCI"])):
        try:
            from vnstock import Quote
            quote=Quote(source=provider,symbol=symbol)
            try: raw=quote.history(start=start,end=end,interval="1D")
            except TypeError: raw=quote.history(start_date=start,end_date=end)
            return _standardize(raw), f"Vnstock Quote / {provider}"
        except Exception as exc: errors.append(f"Quote-{provider}:{type(exc).__name__}")
    # Backward-compatible route.
    try:
        from vnstock import Vnstock
        raw=Vnstock().stock(symbol=symbol,source=source).quote.history(start=start,end=end,interval="1D")
        return _standardize(raw), f"Vnstock legacy / {source}"
    except Exception as exc: errors.append(f"Legacy:{type(exc).__name__}")
    raise RuntimeError(" | ".join(errors))


def _cache_path(symbol: str) -> Path:
    safe=re.sub(r"[^A-Za-z0-9_-]","_",symbol.upper())
    return CACHE_DIR / f"{safe}_ohlcv.csv"


def _save_cache(symbol: str, df: pd.DataFrame):
    try:
        CACHE_DIR.mkdir(parents=True,exist_ok=True)
        df.to_csv(_cache_path(symbol),index=False)
    except Exception:
        pass


def _load_cache(symbol: str, start: str, end: str) -> pd.DataFrame | None:
    # V3.3 first reads the sanitized cache generated by refresh_silver_ai.py, then the legacy runtime cache.
    public_cache=Path(__file__).resolve().parent / "data_cache" / f"{re.sub(r'[^A-Za-z0-9_-]', '_', symbol.upper())}_ohlcv.csv"
    for path in [public_cache,_cache_path(symbol)]:
        if not path.exists(): continue
        try:
            df=_standardize(pd.read_csv(path)); mask=(df["date"]>=pd.Timestamp(start))&(df["date"]<=pd.Timestamp(end)); df=df.loc[mask]
            if len(df)>=5:return df
        except Exception: pass
    return None


def _fallback(symbol: str,start: str,end: str,base: float) -> pd.DataFrame:
    dates=pd.bdate_range(start=start,end=end); seed=int(hashlib.sha256(f"{symbol}-{start}-{end}".encode()).hexdigest()[:8],16); rng=np.random.default_rng(seed)
    returns=rng.normal(0.00025,0.011,len(dates)); close=base*np.exp(np.cumsum(returns)); open_=close*(1+rng.normal(0,0.003,len(dates))); high=np.maximum(open_,close)*(1+rng.uniform(0.001,0.009,len(dates))); low=np.minimum(open_,close)*(1-rng.uniform(0.001,0.009,len(dates))); volume=rng.integers(350_000_000,1_200_000_000,len(dates))
    return pd.DataFrame({"date":dates,"open":open_,"high":high,"low":low,"close":close,"volume":volume})


def get_market_data(symbol="VNINDEX",start="2025-01-01",end=None,source="KBS",fallback=True,base=1265.0,allow_live=True):
    end=end or date.today().isoformat(); start=str(start)[:10]; end=str(end)[:10]
    try:
        if not allow_live:
            raise RuntimeError("Live market calls disabled in cloud-safe runtime")
        frame,label=_vnstock(symbol,start,end,source)
        if len(frame)<5: raise ValueError("Insufficient observations")
        _save_cache(symbol,frame)
        return frame,label,None
    except Exception as exc:
        cached=_load_cache(symbol,start,end)
        if cached is not None: return cached,"Vnstock Cache",str(exc)
        if not fallback: raise
        return _fallback(symbol,start,end,float(base)),"Offline illustrative fallback",str(exc)


def market_metrics(df: pd.DataFrame) -> dict:
    frame=df.sort_values("date").copy(); close=frame["close"].dropna(); ret=close.pct_change().dropna(); periods=min(63,len(close)-1)
    last_date=pd.to_datetime(frame.loc[close.index[-1],"date"]); ytd=frame[pd.to_datetime(frame["date"]).dt.year==last_date.year]["close"].dropna()
    high_52w=float(close.tail(252).max()); volume=pd.to_numeric(frame.get("volume"),errors="coerce")
    volume_20d=float(volume.tail(20).mean()) if volume.notna().any() else np.nan
    delta=close.diff(); gain=delta.clip(lower=0).tail(14).mean(); loss=(-delta.clip(upper=0)).tail(14).mean()
    rsi14=float(100-(100/(1+gain/loss))) if pd.notna(loss) and loss>0 else np.nan
    return {
        "level":float(close.iloc[-1]),
        "return_1m":float(close.iloc[-1]/close.iloc[max(0,len(close)-22)]-1),
        "return_3m":float(close.iloc[-1]/close.iloc[-1-periods]-1) if periods else 0.0,
        "return_ytd":float(ytd.iloc[-1]/ytd.iloc[0]-1) if len(ytd)>1 else 0.0,
        "volatility":float(ret.tail(20).std()*np.sqrt(252)) if len(ret)>1 else 0.0,
        "drawdown":float(close.iloc[-1]/close.cummax().iloc[-1]-1),
        "distance_52w_high":float(close.iloc[-1]/high_52w-1) if high_52w else 0.0,
        "ma20":float(close.tail(20).mean()), "ma50":float(close.tail(50).mean()), "ma200":float(close.tail(200).mean()),
        "volume_latest":float(volume.iloc[-1]) if len(volume) and pd.notna(volume.iloc[-1]) else np.nan,
        "volume_20d_avg":volume_20d,
        "volume_ratio_20d":float(volume.iloc[-1]/volume_20d) if pd.notna(volume_20d) and volume_20d>0 else np.nan,
        "rsi14":rsi14,
    }


def market_technical_frame(df: pd.DataFrame) -> pd.DataFrame:
    out=df.sort_values("date").copy()
    out["MA20"]=out["close"].rolling(20).mean(); out["MA50"]=out["close"].rolling(50).mean(); out["MA200"]=out["close"].rolling(200).mean()
    delta=out["close"].diff(); gain=delta.clip(lower=0).rolling(14).mean(); loss=(-delta.clip(upper=0)).rolling(14).mean(); rs=gain/loss.replace(0,np.nan)
    out["RSI14"]=100-(100/(1+rs)); out["Volume_MA20"]=pd.to_numeric(out["volume"],errors="coerce").rolling(20).mean()
    return out


def market_regime(metrics: dict) -> str:
    if metrics["drawdown"]<=-0.12 or metrics["return_3m"]<=-0.08:return "STRESS"
    if metrics["return_3m"]>=0.08 and metrics["drawdown"]>-0.05:return "RISK-ON"
    if metrics["return_3m"]<0:return "RISK-OFF"
    return "NEUTRAL"
